package airvia.airvialtd;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.stage.Stage;

import java.io.IOException;

/**
 * This class represents the controller for the Sysadmin view, which allows the system administrator to manage the system.
 */
public class SysadminController {

    private Stage stage;
    private Scene scene;

    @FXML
    private Button homeButton;

    @FXML
    private Button reportButton;

    @FXML
    private Button settingButton;

    @FXML
    private Button stockButton;

    @FXML
    private Button userAccountButton;

    @FXML
    private Button logOutButton;

    /**
     * Handles the "Log Out" button click event by loading the "Login.fxml" file and displaying it in the current stage.
     *
     * @param event the ActionEvent triggered by clicking the "Log Out" button
     * @throws IOException if an I/O error occurs while loading the FXML file
     */
    @FXML
    void logOutButtonClick(ActionEvent event) throws IOException{
        // Load the "Login.fxml" file
        Parent root = FXMLLoader.load(Main.class.getResource("Login.fxml"));

        // Get the current stage
        stage = (Stage) ((Node)event.getSource()).getScene().getWindow();

        // Set the scene with the "Login.fxml" file
        scene = new Scene(root);
        stage.setScene(scene);

        // Display the current stage
        stage.show();
    }


    /**
     * Handles the "Home" button click event by loading the "SysadminHome.fxml" file and displaying it in the current stage.
     *
     * @param event the ActionEvent triggered by clicking the "Home" button
     * @throws IOException if an I/O error occurs while loading the FXML file
     */
    @FXML
    void homeButtonClick(ActionEvent event) throws IOException {
        // Load the "SysadminHome.fxml" file
        Parent root = FXMLLoader.load(Main.class.getResource("SysadminHome.fxml"));

        // Get the current stage
        stage = (Stage) ((Node)event.getSource()).getScene().getWindow();

        // Set the scene with the "SysadminHome.fxml" file
        scene = new Scene(root);
        stage.setScene(scene);

        // Display the current stage
        stage.show();
    }


    /**
     * Event handler method for the "Reports" button on the System Admin UI.
     *
     * Loads the SysadminReports.fxml file and displays it in the current window.
     *
     * @param event The ActionEvent that triggered this method.
     * @throws IOException If there is an error loading the FXML file.
     */
    @FXML
    void reportButtonClick(ActionEvent event) throws IOException {
        System.out.println("report");
        Parent root = FXMLLoader.load(Main.class.getResource("SysadminReports.fxml"));
        stage = (Stage) ((Node)event.getSource()).getScene().getWindow();
        scene = new Scene(root);
        stage.setScene(scene);
        stage.show();
    }

    /**
     * Handles the "Setting" button click event by loading the "SysadminSettingGeneral.fxml" file and displaying it in the current stage.
     *
     * @param event the ActionEvent triggered by clicking the "Setting" button
     * @throws IOException if an I/O error occurs while loading the FXML file
     */
    @FXML
    void settingButtonClick(ActionEvent event) throws IOException {
        // Load the "SysadminSettingGeneral.fxml" file
        Parent root = FXMLLoader.load(Main.class.getResource("SysadminSettingGeneral.fxml"));

        // Get the current stage
        stage = (Stage) ((Node)event.getSource()).getScene().getWindow();

        // Set the scene with the "SysadminSettingGeneral.fxml" file
        scene = new Scene(root);
        stage.setScene(scene);

        // Display the current stage
        stage.show();
    }


    /**
     * This method handles the click event of the blank button in the Sysadmin view.
     *
     * @param event The action event generated by the button click
     * @throws IOException If an I/O error occurs while loading the SysadminBlank.fxml file
     */
    @FXML
    void blankButtonClick(ActionEvent event) throws IOException {
        // Load the SysadminBlank.fxml file using the FXMLLoader
        Parent root = FXMLLoader.load(Main.class.getResource("SysadminBlank.fxml"));

        // Get the current window (stage) where the button was clicked and set its scene to the loaded root
        stage = (Stage) ((Node)event.getSource()).getScene().getWindow();
        scene = new Scene(root);
        stage.setScene(scene);

        // Show the stage with the updated scene
        stage.show();
    }


    /**
     * This method handles the click event of the user account button in the Sysadmin view.
     *
     * @param event The action event generated by the button click
     * @throws IOException If an I/O error occurs while loading the SysadminUserAccount.fxml file
     */
    @FXML
    void userAccountButtonClick(ActionEvent event) throws IOException {
        // Load the SysadminUserAccount.fxml file using the FXMLLoader
        Parent root = FXMLLoader.load(Main.class.getResource("SysadminUserAccount.fxml"));

        // Get the current window (stage) where the button was clicked and set its scene to the loaded root
        stage = (Stage) ((Node)event.getSource()).getScene().getWindow();
        scene = new Scene(root);
        stage.setScene(scene);

        // Show the stage with the updated scene
        stage.show();
    }


}
